### ISSUE TITLE
Calculo de parcelamento está errado

### ISSUE THREAD

**Issue by sixbank-dev** [sixbank/Magento2-Plugin#10]
O calculo de parcelamento esta errado, o valor total está apenas dividindo o valor total pelo numero da parcela, e ignorando o valor de juros composto.

Aqui um site que explica como calcular o total de cada parcela baseado no calculo de juros composto.

https://ajuda.eduzz.com/?article=compras-parceladas-com-taxa-de-292

![image](https://user-images.githubusercontent.com/53960192/68695760-66e99100-055a-11ea-9ca1-eb5e5abdcfd6.png)

**Comment by brunoetap** [comment]
Fiz os testes calculando, e parece correto seguindo esse site, e também a calculadora abaixo
https://www3.bcb.gov.br/CALCIDADAO/publico/calcularFinanciamentoPrestacoesFixas.do
Os testes na calculado com o mesmo valor do site que indicou batem. Também conferi com o WooCommerce e bateram também. Pode conferir novamente?
