### ISSUE TITLE
Campos de RG e Telefone deve existir um campo para definir se é obrigatório ou não.

### ISSUE THREAD

**Issue by sixbank-dev** [sixbank/Magento2-Plugin#14]

**Comment by sixbank-dev** [comment]
![image](https://user-images.githubusercontent.com/53960192/68782635-7deeb880-0618-11ea-9e38-7245f0320585.png)

**Comment by sixbank-dev** [comment]
Campos continuam como obrigatórios, não achei onde é setado a config se deve ser exigido esses dados no checkout.

**Comment by brunoetap** [comment]
A configuração é em Stores > Payment Methods > Sixbank - General Settings
