### ISSUE TITLE
Campo data de validade do cartao permite mês acima de 12 e ano menor que 19

### ISSUE THREAD

**Issue by sixbank-dev** [sixbank/Magento2-Plugin#17]

**Comment by sixbank-dev** [comment]
![image](https://user-images.githubusercontent.com/53960192/69530400-bc597100-0f50-11ea-840e-b58b1e46753c.png)

A validacao nao esta ocorrendo no via front, quando retorna o erro do backend o cliente nao sabe o que esta errado.

validar no front

**Comment by sixbank-dev** [comment]
erro voltou
![image](https://user-images.githubusercontent.com/53960192/69573568-23a11080-0fa5-11ea-8f76-aff844e47ab8.png)

aba nova e anonima

**Comment by sixbank-dev** [comment]
mesmo erro ainda
![image](https://user-images.githubusercontent.com/53960192/69696959-0ca31100-10c0-11ea-9188-03d2a20334ba.png)

**Comment by sixbank-dev** [comment]
estou usando chrome no mac .. por favor testar ainda de liberar para validar

**Comment by brunoetap** [comment]
Fizemos o teste no MAC com Chrome, foi OK
Se acontecer novamente, tentar só limpar o cache, e se der gravar o fluxo que está fazendo para tentarmos reproduzir

**Comment by sixbank-dev** [comment]
![image](https://user-images.githubusercontent.com/53960192/69959347-b67e0580-14e5-11ea-8c36-2d37fe05efa0.png)

mesmo erro ainda  .. estou debungando com limpeza de cache e aba anonima
