### ISSUE TITLE
Botão para capturar uma transação

### ISSUE THREAD

**Issue by sixbank-dev** [sixbank/Magento2-Plugin#4]
Não foi encontrado a opção de capturar um pagamento, quando em configurações de pagamento esta setado para captura posterior.

O cliente compra, porem é somente autorizado. 
O lojista deve entrar no pedido e tera opcao de capturar ou cancelar o pedido.

**Comment by brunoetap** [comment]
Para fazer a captura automática, entrar no detalhe da venda > Invoce, deixar selecionado Capture Online

**Comment by sixbank-dev** [comment]
Ficou muito escondido essa ação que é muito importante para o lojista. deixar a opcao de capturar do mesmo modo que  tratado um cancelamento

Colocar antes de cancel a opcao Capture

![image](https://user-images.githubusercontent.com/53960192/68689092-9db9aa00-054e-11ea-9a0a-56c01ccc55be.png)

**Comment by sixbank-dev** [comment]
Ao tentar capturar uma transacao via painel

![image](https://user-images.githubusercontent.com/53960192/68779895-28b0a800-0614-11ea-8351-5b4c165b78e7.png)
